version: "3.6"
services:

  app1:
    container_name: app1
    build:
      context: ./app1
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - share-data:/var/share
    hostname: ubuntu1
    networks:
      - simple-network
    restart: always
    stdin_open: true
    tty: true

  app2:
    container_name: app2
    build:
      context: ./app2
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - share-data:/var/share
    hostname: centos2
    networks:
      - simple-network
    restart: always
    stdin_open: true
    tty: true

networks:
  simple-network:
    driver: bridge

volumes:
  share-data:
    driver: local
